import os
import json

india_traffic_handbook = """S1 Driving side & lane discipline: In India you drive on the left. As a default, keep left unless road markings, signs, or a turning manoeuvre require otherwise; move right to overtake, to position for a right turn, or to avoid an obstruction, then return left when safe. Where lanes are marked, drive within the lane and change lanes only after giving a proper signal.

S2 Speed limits are in km/h (not mph). Always follow posted speed-limit signs and road-specific restrictions. A notable nationwide special rule is that, when passing a construction site, school, or hospital where indicated by signage, or on roads without footpaths/soft shoulders where pedestrians use part of the carriageway, the speed must not exceed 25 km/h or such lower speed as may be signed.

S3 Lane markings & special lanes: Where a lane is specially marked for a class of vehicles or for a special purpose, only that class may use it. Do not cross a continuous solid longitudinal line in order to overtake, and do not drive over painted traffic islands except to avoid an obstruction. Use the correct marked turning lane when approaching an intersection.

S4 Traffic lights & manual control: Obey traffic lights unless a police officer or authorised person is manually controlling traffic, in which case the officer’s directions override the signals. Red means stop before the stop line, crosswalk, or primary signal; yellow means stop unless abrupt braking would be unsafe; green means proceed only if the way ahead is clear. Flashing red requires stopping and then proceeding only after yielding, while flashing amber means slow down and proceed with caution.

S5 Left turn on red: A major India-specific rule is that a motor vehicle may generally take a left turn at a red signal unless a traffic control device or a road sign prohibits it. Even when left turn on red is allowed, the driver must first give way to traffic approaching from the right, and to pedestrians and cyclists crossing on the driver’s left side.

S6 Junction priority, STOP / GIVE WAY, and blocked intersections: At a STOP sign, stop fully and give way to traffic on the major road. At a GIVE WAY sign, slow down and yield before proceeding. At uncontrolled intersections and junctions, vehicles approaching from the right have the right of way unless the junction is otherwise controlled or one vehicle is emerging from a minor road onto a major road. Do not enter an intersection if traffic has already come to a standstill, even if you are on the main road or have a signal to proceed.

S7 Roundabouts: While entering a roundabout, traffic already in the roundabout has the right of way. Choose the lane appropriate to your intended movement before entering, use indicators when changing lanes within the roundabout, and exit carefully in accordance with lane discipline and left-side driving.

S8 Turning behaviour & vulnerable road users: Plan turns well in advance, signal clearly, and move into the correct lane before turning. For a left turn, move to the left-most lane or slip lane where provided and give way to cyclists, other slow-moving traffic, and pedestrians at uncontrolled crossings. For a right turn, move to the right-most lane in good time and give way to road users who already have the right of way. U-turns must not be made where prohibited, across solid lines, on busy roads with continuous flow, or on major roads, highways, or expressways.

S9 Overtaking: In India, overtaking is normally only from the right side. Passing on the left is allowed only in limited cases, such as on a marked multi-lane road where it is safe, when the vehicle ahead is turning right or making a U-turn, or when the vehicle ahead is stationary. Do not overtake if the traffic situation is unclear, if a sign prohibits it, or by crossing a continuous solid line.

S10 Railway crossings: Rail-borne vehicles have overriding priority at unmanned level crossings. Slow down when approaching a railway crossing, do not park or overtake within the barriers, and keep to the left. At a guarded crossing, do not enter after the barriers have closed or started to close, or when facing a red light. At an unguarded crossing, enter only after ensuring no train is in sight; buses, school buses, goods vehicles, tractor trolleys, and vehicles carrying hazardous goods have additional stop-and-check duties.

S11 Tunnels and mountain roads: Before entering a tunnel, switch on dipped lights. Inside a tunnel, do not overtake, make a U-turn, or drive backwards, and do not stop or park unless absolutely unavoidable. On mountain roads or steep roads that are too narrow for two vehicles to cross freely, the downhill vehicle must stop on the left and allow the uphill vehicle to pass first.

S12 Stopping, parking & yellow-box control: A vehicle must not stop on or five meters before a pedestrian crossing, on a level crossing, in an acceleration or deceleration lane, at a bus stand if it is not a bus, or on a yellow box. A vehicle must not be parked on footpaths, cycle tracks, pedestrian crossings, in tunnels, in bus lanes, or where “No Parking” applies. Do not stop or park in a way that blocks access, signs, hydrants, intersections, or other traffic.

S13 Horns and silence zones: Unnecessary use of the horn is prohibited. As far as possible, the horn should be used only when the driver apprehends danger. Drivers must not sound the horn continuously or repeatedly, or in residential areas or silence zones indicated by a mandatory sign. Air horns and harsh, shrill, or multi-toned horns are generally prohibited except for designated emergency vehicles on duty. India also uses a mandatory “Compulsory sound horn” sign in some locations.

S14 Emergency vehicles & breakdown procedures: Emergency vehicles using the prescribed multi-toned horn and flasher have the right of way over all other vehicles. Other drivers must move left as close as practicable to the kerb or road edge, stop if required, and remain stationary until the emergency vehicle has passed. In a breakdown involving a vehicle with more than two wheels, switch on hazard warning lights immediately; on highways and major fast roads, place reflective warning triangles at least 50 meters behind the vehicle, and take extra precautions around bends.

S15 Distinctive Indian road features & signs: India’s signed road environment includes several cues that are especially useful for perception and regional-context tasks: compulsory keep left, compulsory cycle track, STOP, GIVE WAY, pedestrian crossing, school ahead, speed breaker, cattle, ferry, no entry, one way, and compulsory sound horn signs. These signs, together with common mixed-traffic conditions involving bicycles, two-wheelers, auto-rickshaws, pedestrians, and sometimes animals, are important contextual features when interpreting Indian road scenes."""
